### ISSUE TITLE
Saving the czi split channel files as tiff files not working

### ISSUE THREAD

**Issue by keshavprasadgubbi** [keshavprasadgubbi/FishlineAutomation#1]
This error occurs intermittently, some time occurring for the same file and sometimes not, with all other factors being unchanged. Related to line 45 in czi.py.

_```
Traceback (most recent call last):
  File "C:/Users/keshavgubbi/Desktop/ATLAS/S1/czi.py", line 45, in <module>
    with tiff.TiffWriter(os.path.join(c_path, f'{name}_ch{ch_num}.tif')) as tifw:
  File "C:\Users\keshavgubbi\Anaconda3\lib\site-packages\tifffile\tifffile.py", line 1129, in __init__
    self._fh = FileHandle(file, mode='wb', size=0)
  File "C:\Users\keshavgubbi\Anaconda3\lib\site-packages\tifffile\tifffile.py", line 8831, in __init__
    self.open()
  File "C:\Users\keshavgubbi\Anaconda3\lib\site-packages\tifffile\tifffile.py", line 8844, in open
    self._fh = open(self._file, self._mode)
OSError: [Errno 22] Invalid argument: 'C:\\Users\\keshavgubbi\\Desktop\\ATLAS\\S1\\data\\czidata\\2_ch0.tif'
```_

**Comment by keshavprasadgubbi** [comment]
Traceback (most recent call last):
  File "C:/Users/keshavgubbi/Desktop/ATLAS/S1/czi.py", line 23, in <module>
    czi = CziFile(os.path.join(c_path, file))
  File "C:\Users\keshavgubbi\Anaconda3\lib\site-packages\aicspylibczi\CziFile.py", line 57, in __init__
    self.reader = self.czilib.Reader(self._bytes)
RuntimeError: Illegal data detected at offset 0 -> Invalid FileHdr-magic

**Comment by joe311** [comment]
Check whether file handles are open: 
https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer (or https://docs.microsoft.com/en-us/sysinternals/downloads/handle)
